name = "HexMC Server Config"
author = "Tabzlock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d3a02097d50f1b45463b600ea297f0bf80e3d65d7933f4e5a5d61302080dc3"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
