name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0acfd6939f736716294d1c835a742d9f835d03c742eb2dea5655239dbabc0a5c"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
