name = "HexMC"
author = "HexMC Contributors"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86187987879c4ee7f13078a7640d1ef6709d91357302859602480d6111d0dae4"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
