name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2696fa941813bb6a11ba3c54b496061befdd7dd3a49fd2c94dc04639502e413d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
