name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80b8d18aed4b7166581bfbba9eabdeb8ac3dc7c75421535112f02288362ac008"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
