name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a35f0b2bdd11662a79c01d3488bd8031783045068acbd51e11525b67616a622"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
