name = "HexMC"
author = "HexMC Contributors"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "028ed1e04d3b9f5269a929272e92129b7e242191787b8640bd9b4f088a3ba048"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
