name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f58a500a05156013349b20dd0e5ec862683a032ca128ab5061389fade797d13"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
