name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d081808593fd78a0db4dce0d4001c67b4704e95262b5c72b702f4738d40c50d2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
