name = "HexMC"
author = "HexMC Contributors"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "332bbd68bedeba207d9c1f15eae4c98045d929e387a870db23200d00ad47e51f"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
