name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4b7939958c106149cf387a215368b82254d0667403618b97ef63dcab320a28a"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
