name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "255ba84fbcf6dd80c5290e3b0b0cc663eb7a5e28eb1ad83e03647cccc66a2039"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
