name = "HexMC"
author = "Tabzlock"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afe8240070b7994460f0b781ab391ce242b7e6553bce248a43878252ca581b9d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
